config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :users, only: [:show, :edit, :update, :destroy]
  
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :conversations do
    resources :messages
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :user
	has_many :messages
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :conversation
	belongs_to :user
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :conversations
	has_many :messages
	validates_format_of :email, :with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
	validates :email, :username, presence: true
    validates :email, :username, uniqueness: true
    validates :password, :length => {minimum: 4}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	def new
		@conversation = Conversation.new
	end

	def create
		@conversation = Conversation.new(conversation_params)

		if @conversation.save
			redirect_to @conversation
		else
			render 'new'
		end
	end

	def show
		@conversation = Conversation.find(params[:id])
		@message = Message.new
	end

	private
		def conversation_params
			params.require(:conversation).permit(:title)
		end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create
		@conversation = Conversation.find(params[:conversation_id])
		@message = Message.new(message_params)
		@message.conversation_id = params[:conversation_id]

		if @message.save
			redirect_to @conversation
		else
			render 'show'
		end

	end

	private
	def message_params
		params.require(:message).permit(:comment, :picture, :remote_picture_url)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(:email => params[:email])
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id

			redirect_to root_url
		else
			render :new
		end
	end

	def destroy
		session.clear
		redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_url
		else
			render 'new'
		end
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.find(session[:user_id]) if session[:user_id]
  	@messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/conversations/_form.html.erb
<%= form_for @conversation do |f| %>
  <% if @conversation.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@conversation.errors.count, "error") %> prohibited
      this conversation from being saved:</h2>
    <ul>
    <% @conversation.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/conversations/new.html.erb
<h1>Create a new conversation!</h1>

<p>To create a conversation, simply upload a picture, and type in a comment. Then, send it to friends, or have them find it here!</p>

<%= render 'form' %>

app/views/conversations/show.html.erb
<h1><%= @conversation.title %></h1>

<p>Create a new message!</p>

<%= form_for([@conversation, @message], :html => {:multipart => true}) do |f| %>
<% if @message.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@message.errors.count, "error") %> prohibited
      this message from being saved:</h2>
    <ul>
    <% @message.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
  	<%= f.label :picture %><br>
  	<%= f.file_field :picture %>
  </p>

  <p>
    <%= f.label :remote_picture_url, "or image URL" %>
    <%= f.text_field :remote_picture_url %>
  </p>

  <p>
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %> 

<% @conversation.messages.each do |message| %>
	<%= image_tag message.picture_url(:thumb).to_s %>
	<%= message.comment %>
	<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PictureConvo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav>

    <div class="left">
        <li><h2>PictureConvo</h2></li>
        <li><%= link_to 'Home', root_path %></li>
    </div>

      

    <div class="right">
      <% if session[:user_id] %>
      <li> <%= link_to 'Logout', logout_path, method: :delete %></li>
      <% else %>
      <li><%= link_to 'Login', login_path %></li>
      <li> <%= link_to 'Signup', signup_path %></li>
      <% end %>
  </div>
  </nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<br>
<%= form_for :user, url: signup_path do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit value:"Sign Up!" %>
  </p>
<% end %>

app/views/welcome/index.html.erb
<h1>PictureConvo</h1>
<h2>Have conversations with your friends using pictures!</h2>

<% if @user %>
<h2>Hello, <%= @user.username %></h2>
<%= link_to "Create Conversation", new_conversation_path %>
<% end %>

<% @messages.each do |message| %>
	<div class="mini"><%= image_tag message.picture_url(:mini).to_s %></div>
<% end %>